### ISSUE TITLE
Apply the schema on a model prototype rather than an instance

### ISSUE THREAD

**Issue by uzikilon** [dnemoga/Backbone.Schema#19]
For my use case, it will be much better to be able to assign a schema for a model definition rather than an instance.
This way you define the model once, and any instance of it will share the same behavior.
```javascript
var Model = Backbone.Model.extend({
  schema: {
    'boolean-property', {type: 'boolean'}
  }
});
```
or 
```javascript
var Model = Backbone.Model.extend({}),
    schema = new Backbone.Schema(Model);
schema.define('string-property', {type: 'string' });

```

**Comment by alexpusch** [comment]
Just create the scheme in the Models initialize method.
