### ISSUE TITLE
Make defining of all attributes not required

### ISSUE THREAD

**Issue by amq627yu** [dnemoga/Backbone.Schema#23]
As we see f.e. [here](../blob/master/src/backbone/schema.js#L43) or [here](../blob/master/src/backbone/schema.js#L65) all attributes must be defined in the schema, otherwise we'll  get error like:

```
Uncaught TypeError: Cannot read property 'toJSON' of undefined
```

What is pretty annoying, especially during active development.
So, idea is to check this attribute in the schema and if it not defined - just return result.
This can be made as a mode - as on me, it's good to have "soft" and "strict" mode.

ПС
Питання чи впишеться це в ідеологію бібліотеки. Якщо так - з мене pull request

**Comment by alexpusch** [comment]
I don't see a need for "modes", it's just a bug. Will fix soon. Thanks for the heads up!

**Comment by amq627yu** [comment]
thank you!
looking forward to fixing
